# Service Bus definitions per environment
buses:
  - Name: insizon-bus
    Env: dev
    Location: centralus
    Sku: Standard  # Options: Basic, Standard, Premium
    Topics:
      - name: new-user-topic
        MaxTopicSize: 1024     # [1024 2048 3072 4096 5120 10240 20480 40960 81920]
        MessageTTL: "P14D"     # 14 days
        TargetApp: insizon-app-dev

    Queues:
      - name: notification-queue
        MaxDeliveryCount: 5
        MessageTTL: "PT2H"     # 2 hours
        TargetApp: insizon-app-dev
