# Static file upload instructions to Azure Blob Storage
files:
  - FolderName: public
    StorageAccountName: insizon-static-bucket
    ContainerName: public-assets
    EnableStaticWebsite: false
    StaticWebsiteIndex: index.html
    Error404Document: 404.html

    FilesExcluded:
      - secret.txt

    CustomDomain: static.insizon.muhammadhassaanjaved.com
    